<pre class=metadata>
Group: test
Shortname: test
Level: 1
Status: LS
ED: http://example.com/foo
Editor: Example Editor
Date: 1970-01-01
Title: HTML Highlighting
Abstract: Some examples of HTML highlighting that were problematic, particularly with &lt;wbr> and initial whitespace.
</pre>

<p>
<code highlight="html"> &lt;ruby&gt;<wbr>&lt;rb&gt;<wbr>旧&lt;rb&gt;<wbr>金&lt;rb&gt;<wbr>山&lt;rp&gt;<wbr> (&lt;rt&gt;<wbr>jiù&lt;rt&gt;<wbr>jīn&lt;rt&gt;<wbr>shān&lt;rtc&gt;<wbr>&lt;rp&gt;<wbr>: &lt;/rp&gt;<wbr>San Francisco&lt;/rtc&gt;<wbr>&lt;rp&gt;<wbr>)&lt;/ruby>
</code>

<p>
<code highlight="html"> &lt;ruby>&#x200b;&lt;rb>&#x200b;旧&lt;rb>&#x200b;金&lt;rb>&#x200b;山&lt;rp>&#x200b; (&lt;rt>&#x200b;jiù&lt;rt>&#x200b;jīn&lt;rt>&#x200b;shān&lt;rtc>&#x200b;&lt;rp>&#x200b;: &lt;/rp>&#x200b;San Francisco&lt;/rtc>&#x200b;&lt;rp>&#x200b;)&lt;/ruby>
</code>

<p>
<code highlight="html">
	&lt;ruby>&#x200b;&lt;rb>&#x200b;旧&lt;rb>&#x200b;金&lt;rb>&#x200b;山&lt;rp>&#x200b; (&lt;rt>&#x200b;jiù&lt;rt>&#x200b;jīn&lt;rt>&#x200b;shān&lt;rtc>&#x200b;&lt;rp>&#x200b;: &lt;/rp>&#x200b;San Francisco&lt;/rtc>&#x200b;&lt;rp>&#x200b;)&lt;/ruby>
</code>


<p>
<code highlight="html"> &lt;ruby><wbr>&lt;rb><wbr>旧&lt;rb><wbr>金&lt;rb><wbr>山&lt;rp><wbr> (&lt;rt><wbr>jiù&lt;rt><wbr>jīn&lt;rt><wbr>shān&lt;rtc><wbr>&lt;rp><wbr>: &lt;/rp><wbr>San Francisco&lt;/rtc><wbr>&lt;rp><wbr>)&lt;/ruby>
</code>

<p>
<code highlight="html">
	&lt;ruby><wbr>&lt;rb><wbr>旧&lt;rb><wbr>金&lt;rb><wbr>山&lt;rp><wbr> (&lt;rt><wbr>jiù&lt;rt><wbr>jīn&lt;rt><wbr>shān&lt;rtc><wbr>&lt;rp><wbr>: &lt;/rp><wbr>San Francisco&lt;/rtc><wbr>&lt;rp><wbr>)&lt;/ruby>
</code>
