name: Update Fork
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          upstream_repo: "https://github.com/speced/bikeshed.git"
          upstream_branch: main
          downstream_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
